### ISSUE TITLE
Resource Groups deprecation/removal

### ISSUE THREAD

**Issue by MichielDeMey** [apiaryio/api-blueprint-ast#32]
Hi

When will Resource Groups (now deprecated) be removed from the spec?
I noticed it's still used a lot throughout the open-source community, so  I assume it will be for version 1B?

Michiel

**Comment by zdne** [comment]
Hey @MichielDeMey no ETA yet. We want to support is as long as needed / used however we want to migrate towards a more general way of categorization (grouping) of elements in a future. So while in a sense the resource groups will go, the functionality of grouping should stay there – it will be only replaced by a more generic "grouping element".

**Comment by pksunkara** [comment]
As of 2015-12-02 the API Blueprint AST is deprecated and should not be used for new development. The API Blueprint AST has been superseded by [API Description Refract Namespace](https://github.com/refractproject/refract-spec/blob/master/namespaces/api-description-namespace.md).

You can still get the API Blueprint AST from the parser by passing the appropriate option but please understand that we will not be maintaining it anymore.
