### ISSUE TITLE
`element` causing confusion

### ISSUE THREAD

**Issue by pzurek** [apiaryio/api-blueprint-ast#35]
Hey guys,

This is more of a suggestion or rfc rather than an issue. I have started working on a tool (or a series of tools if all goes well) that use the AST (from drafter.js) to do some interesting things.
When trying to understand the structure of the AST I found the duality of the term `element` really confusing and I think it could be easily fixed.
So first of all one of objects of the AST is called Element, and then secondly that objects includes a property called `element` describing the type of the element. I think it would be much more descriptive if the property was actually called `type` bringing this in line with general programming nomenclature.
If that was the case, my Go code instead of this:

```go
type Element struct {
	Element string `json:"element"`
	...
}
```

would look like that:

```go
type Element struct {
	Type string `json:"type"`
	...
}
```

This feels so much cleaner and more descriptive to me.

What do you think?

**Comment by zdne** [comment]
Hey @pzurek, you are indeed right – the current state of AST is a bit of mess. We are collaboratively working on two radical improvements: 

1. Simplify, tighten and clarify the AST
2. Provide a SDK to interact with the API description

When it comes to the first point we will have a whole new version of API (description) DOM to replace the AST soon™. It will be based on the refract project – https://github.com/refractproject/refract-spec – recursive elements separating data structure from the semantics.

I believe the result will be much cleaner tree that is actually easier to manipulate even without any SDKs.

Of, course the parser toolchain will be still providing this original AST. 

I would love to hear any comments or ideas you may have! 

Thanks!

**Comment by pzurek** [comment]
I think the element -> type is the most obvious problem that I found quite irritating. I was a bit bummed out to find it in the refract spec too. If feels so obvious to me that I feel like you guys must have had a good reason not to call it `type`.
Other than that I find it a bit hard to deal with the `content` element. The fact that it can be either a string or a object or an array of objects makes it much harder to parse the JSON in a static language like.

**Comment by LinusU** [comment]
I couldn't agree more with @pzurek, `type` seems like the obvious choice.

I also find the refract spec a bit strange, it seems that I sometimes can use `meta`, sometimes `attributes`. It really seems like it's trying to reinvent the DOM that the browsers are using, and thus I think that they should take some inspiration from there.

The point about `content` is spot on, I think that it should always be an array of other nodes. [The DOM Node interface](http://www.w3.org/TR/domcore/#interface-node) is really nice.

**Comment by LinusU** [comment]
@pzurek Please check out refractproject/refract-spec#21

**Comment by zdne** [comment]
@pzurek  @LinusU I can only add https://twitter.com/zdne/status/544866242084233216 :smile_cat:

**Comment by zdne** [comment]
Either way we can ask @smizell directly for the reasoning. Also consider the compact notation which is essentially a tuple.

**Comment by zdne** [comment]
Also if you are in JavaScript it is worth checking Fury.js – our upcoming SDK for manipulation with (not) API Blueprint

**Comment by LinusU** [comment]
@zdne Would you mind elaborating on why you should never name a variable `type`? I don't really understand and your tweet dosen't really provide any precedence as to why one would wan't to avoid it.

I might be getting this totally wrong but it seems like what `Fury.js` does is bring back the deprecated structure. `resourceGroups` (array[Resource Group]), `resources` (array[Resource])...

It seems quite backwards to deprecate a data structure to then bring it back thru an sdk that you are now recommending people to use. But as I said, I've probably missed something.

**Comment by LinusU** [comment]
Actually, the more I understand I get less excited on switching the ast to that. It supports a wide range of advanced features that we will never use, but that users of the ast will have to account should they want to accept any ast.

Refract allows recursive elements which will never occur here. If care is not taken it could allow a user to upload a malicious ast to the apiary service that would result in an infinite loop.

Refract allows anything to be elements and to reference other elements; this is really cool but again is not good at all in this case. It means that the following `meta` would be valid, but it would be really hard to read out the name.

```javascript
{
  meta: [{
    element: "property",
    meta: [{
      element: "string",
      content: "name"
    }],
    content: [{
      element: "string",
      content: "My name"
    }]
  }]
}
```

If we stuck to a simpler approach, the only way to validly specify the name would be something like this:

```javascript
{
  name: "My name"
}
```

I think that a DOM suits API Blueprint really well

**Comment by pzurek** [comment]
@LinusU My exact feelings about recursive elements. This new approach seems to me like the team is working towards some bigger goal which is not very clear to us, mere bystanders. :-)
It feels like the simplicity and focus on core functionality is traded for flexibility which may not be necessary. From my, very superficial point of view of course.

**Comment by zdne** [comment]
@pzurek @LinusU Fair points. I will sit down with @smizell and @danielgtaylor and try to write some sort of short summary and explanation to provide a bigger in-depth into what and why is happening! I will keep you posted here!

Thanks for your support guys! I am really happy for getting the feedback from you!

**Comment by pksunkara** [comment]
As of 2015-12-02 the API Blueprint AST is deprecated and should not be used for new development. The API Blueprint AST has been superseded by [API Description Refract Namespace](https://github.com/refractproject/refract-spec/blob/master/namespaces/api-description-namespace.md).

You can still get the API Blueprint AST from the parser by passing the appropriate option but please understand that we will not be maintaining it anymore.

**Comment by pksunkara** [comment]
I am closing this issue. If you guys want to discuss the refract-spec, please do so at https://github.com/refractproject/refract-spec
