### ISSUE TITLE
parameters' enumerated values are missing description property in AST

### ISSUE THREAD

**Issue by blech75** [apiaryio/api-blueprint-ast#38]
The API Blueprint spec allows for enumerated values of parameters [to each have a description](https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#uri-parameters-section):
```
+ <parameter name>: `<example value>` (<type> | enum[<type>], required | optional) - <description>

    <additional description>

    + Default: `<default value>`

    + Members
        + `<enumeration value 1>` - <enumeration description 1>
        [...]
```

The AST, however, [exposes the enumeration value, but not the description](https://github.com/apiaryio/api-blueprint-ast#parameter-object):
```
Properties
* [...]
* values (array) - An array enumerating possible parameter values
  * (object)
    * value (string) - Value choice of for the parameter
```

I'd expect that the description should also be provided in the AST. Without it, the documentation cannot show the description provided in the API Blueprint doc.

**Comment by pksunkara** [comment]
@blech75 Can you please paste a simple example blueprint? I think I know what is happening here, but I need to check it once.

**Comment by blech75** [comment]
@pksunkara See [this gist](https://gist.github.com/blech75/6265ca9570ec9129f7e1) for a stripped-down and redacted version of a blueprint to demonstrate the value descriptions.

**Comment by pksunkara** [comment]
Thank you @blech75 for the bug report. We will be looking into this but I am afraid I have no ETA.

**Comment by pksunkara** [comment]
@blech75 The descriptions of parameter values were never an actual feature but an accidental bug in the specification.

Also, As of 2015-12-02 the API Blueprint AST is deprecated and should not be used for new development. The API Blueprint AST has been superseded by [API Description Refract Namespace](https://github.com/refractproject/refract-spec/blob/master/namespaces/api-description-namespace.md).

You can still get the API Blueprint AST from the parser by passing the appropriate option but please understand that we will not be maintaining it anymore.
