### ISSUE TITLE
My suggestion for parameter object

### ISSUE THREAD

**Issue by ArtK007** [apiaryio/api-blueprint-ast#39]
Presently the parameter object contains these [properties](https://github.com/apiaryio/api-blueprint-ast#properties-7). Would be more clear if there is another property which describes where the parameter is actually used like whether it is " form" or "body" or "query" parameter etc.

**Comment by zdne** [comment]
Hey @ArtK007, thanks for your feedback! Currently the API Blueprint distinguishes only between URI templates variables – "parameters" and body attributes – "attributes". 

As for the API Blueprint AST – we are currently in the process of moving towards a different format – [Refract](https://github.com/refractproject/refract-spec/blob/master/namespaces/api-description-namespace.md) as hinted here https://github.com/apiaryio/api-blueprint-ast#future-development.

As a matter of fact you can already get the API Description refract from the latest version of API Blueprint parser – [Drafter](https://github.com/apiaryio/drafter).

**Comment by ArtK007** [comment]
@zdne thanks for the reply, will there be any support to other parameter types by API Blueprint going forward?, if so will it be supported in refract?

**Comment by zdne** [comment]
@ArtK007 it will be possible to type parameters (e.g. number or string) however it is not planned to distinguish between the query and path parameters – href variables at the moment. The body attributes are separated already.

**Comment by pksunkara** [comment]
As of 2015-12-02 the API Blueprint AST is deprecated and should not be used for new development. The API Blueprint AST has been superseded by [API Description Refract Namespace](https://github.com/refractproject/refract-spec/blob/master/namespaces/api-description-namespace.md).

You can still get the API Blueprint AST from the parser by passing the appropriate option but please understand that we will not be maintaining it anymore.
